//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFSpider.CrmWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentGradeOperation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AgentGradeOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentDomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string promotionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string agentManagerField;
        
        private System.Nullable<int> totalTicketNumField;
        
        private System.Nullable<decimal> totalTicketField;
        
        private System.Nullable<decimal> passRateField;
        
        private System.Nullable<decimal> less60minRateField;
        
        private System.Nullable<decimal> orderAlterRateField;
        
        private System.Nullable<decimal> voluntaryRateField;
        
        private System.Nullable<decimal> involuntaryRateField;
        
        private System.Nullable<decimal> complainRateField;
        
        private System.Nullable<decimal> qapassRateField;
        
        private System.Nullable<decimal> phoneAnswerRateField;
        
        private System.Nullable<decimal> messageTimeoutRateField;
        
        private System.Nullable<decimal> qualificationField;
        
        private System.Nullable<decimal> whiteListField;
        
        private System.Nullable<decimal> totalScoreField;
        
        private int statusField;
        
        private System.Nullable<System.DateTime> statDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gradeField;
        
        private System.Nullable<int> CurDateTicketCountField;
        
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agentDomain {
            get {
                return this.agentDomainField;
            }
            set {
                if ((object.ReferenceEquals(this.agentDomainField, value) != true)) {
                    this.agentDomainField = value;
                    this.RaisePropertyChanged("agentDomain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string agentName {
            get {
                return this.agentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.agentNameField, value) != true)) {
                    this.agentNameField = value;
                    this.RaisePropertyChanged("agentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string promotion {
            get {
                return this.promotionField;
            }
            set {
                if ((object.ReferenceEquals(this.promotionField, value) != true)) {
                    this.promotionField = value;
                    this.RaisePropertyChanged("promotion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string agentManager {
            get {
                return this.agentManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.agentManagerField, value) != true)) {
                    this.agentManagerField = value;
                    this.RaisePropertyChanged("agentManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> totalTicketNum {
            get {
                return this.totalTicketNumField;
            }
            set {
                if ((this.totalTicketNumField.Equals(value) != true)) {
                    this.totalTicketNumField = value;
                    this.RaisePropertyChanged("totalTicketNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> totalTicket {
            get {
                return this.totalTicketField;
            }
            set {
                if ((this.totalTicketField.Equals(value) != true)) {
                    this.totalTicketField = value;
                    this.RaisePropertyChanged("totalTicket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> passRate {
            get {
                return this.passRateField;
            }
            set {
                if ((this.passRateField.Equals(value) != true)) {
                    this.passRateField = value;
                    this.RaisePropertyChanged("passRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> less60minRate {
            get {
                return this.less60minRateField;
            }
            set {
                if ((this.less60minRateField.Equals(value) != true)) {
                    this.less60minRateField = value;
                    this.RaisePropertyChanged("less60minRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> orderAlterRate {
            get {
                return this.orderAlterRateField;
            }
            set {
                if ((this.orderAlterRateField.Equals(value) != true)) {
                    this.orderAlterRateField = value;
                    this.RaisePropertyChanged("orderAlterRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<decimal> voluntaryRate {
            get {
                return this.voluntaryRateField;
            }
            set {
                if ((this.voluntaryRateField.Equals(value) != true)) {
                    this.voluntaryRateField = value;
                    this.RaisePropertyChanged("voluntaryRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<decimal> involuntaryRate {
            get {
                return this.involuntaryRateField;
            }
            set {
                if ((this.involuntaryRateField.Equals(value) != true)) {
                    this.involuntaryRateField = value;
                    this.RaisePropertyChanged("involuntaryRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<decimal> complainRate {
            get {
                return this.complainRateField;
            }
            set {
                if ((this.complainRateField.Equals(value) != true)) {
                    this.complainRateField = value;
                    this.RaisePropertyChanged("complainRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<decimal> qapassRate {
            get {
                return this.qapassRateField;
            }
            set {
                if ((this.qapassRateField.Equals(value) != true)) {
                    this.qapassRateField = value;
                    this.RaisePropertyChanged("qapassRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<decimal> phoneAnswerRate {
            get {
                return this.phoneAnswerRateField;
            }
            set {
                if ((this.phoneAnswerRateField.Equals(value) != true)) {
                    this.phoneAnswerRateField = value;
                    this.RaisePropertyChanged("phoneAnswerRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<decimal> messageTimeoutRate {
            get {
                return this.messageTimeoutRateField;
            }
            set {
                if ((this.messageTimeoutRateField.Equals(value) != true)) {
                    this.messageTimeoutRateField = value;
                    this.RaisePropertyChanged("messageTimeoutRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<decimal> qualification {
            get {
                return this.qualificationField;
            }
            set {
                if ((this.qualificationField.Equals(value) != true)) {
                    this.qualificationField = value;
                    this.RaisePropertyChanged("qualification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<decimal> whiteList {
            get {
                return this.whiteListField;
            }
            set {
                if ((this.whiteListField.Equals(value) != true)) {
                    this.whiteListField = value;
                    this.RaisePropertyChanged("whiteList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<decimal> totalScore {
            get {
                return this.totalScoreField;
            }
            set {
                if ((this.totalScoreField.Equals(value) != true)) {
                    this.totalScoreField = value;
                    this.RaisePropertyChanged("totalScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<System.DateTime> statDate {
            get {
                return this.statDateField;
            }
            set {
                if ((this.statDateField.Equals(value) != true)) {
                    this.statDateField = value;
                    this.RaisePropertyChanged("statDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string statMonth {
            get {
                return this.statMonthField;
            }
            set {
                if ((object.ReferenceEquals(this.statMonthField, value) != true)) {
                    this.statMonthField = value;
                    this.RaisePropertyChanged("statMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                if ((object.ReferenceEquals(this.gradeField, value) != true)) {
                    this.gradeField = value;
                    this.RaisePropertyChanged("grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<int> CurDateTicketCount {
            get {
                return this.CurDateTicketCountField;
            }
            set {
                if ((this.CurDateTicketCountField.Equals(value) != true)) {
                    this.CurDateTicketCountField = value;
                    this.RaisePropertyChanged("CurDateTicketCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmWebServiceReference.ApiWebServiceSoap")]
    public interface ApiWebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WFSpider.CrmWebServiceReference.HelloWorldResponse HelloWorld(WFSpider.CrmWebServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.HelloWorldResponse> HelloWorldAsync(WFSpider.CrmWebServiceReference.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 itemList 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentGradeOprations", ReplyAction="*")]
        WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse InsertAgentGradeOprations(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentGradeOprations", ReplyAction="*")]
        System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse> InsertAgentGradeOprationsAsync(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WFSpider.CrmWebServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WFSpider.CrmWebServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFSpider.CrmWebServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WFSpider.CrmWebServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAgentGradeOprationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAgentGradeOprations", Namespace="http://tempuri.org/", Order=0)]
        public WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequestBody Body;
        
        public InsertAgentGradeOprationsRequest() {
        }
        
        public InsertAgentGradeOprationsRequest(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAgentGradeOprationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WFSpider.CrmWebServiceReference.AgentGradeOperation[] itemList;
        
        public InsertAgentGradeOprationsRequestBody() {
        }
        
        public InsertAgentGradeOprationsRequestBody(WFSpider.CrmWebServiceReference.AgentGradeOperation[] itemList) {
            this.itemList = itemList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAgentGradeOprationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAgentGradeOprationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponseBody Body;
        
        public InsertAgentGradeOprationsResponse() {
        }
        
        public InsertAgentGradeOprationsResponse(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertAgentGradeOprationsResponseBody {
        
        public InsertAgentGradeOprationsResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiWebServiceSoapChannel : WFSpider.CrmWebServiceReference.ApiWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiWebServiceSoapClient : System.ServiceModel.ClientBase<WFSpider.CrmWebServiceReference.ApiWebServiceSoap>, WFSpider.CrmWebServiceReference.ApiWebServiceSoap {
        
        public ApiWebServiceSoapClient() {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFSpider.CrmWebServiceReference.HelloWorldResponse WFSpider.CrmWebServiceReference.ApiWebServiceSoap.HelloWorld(WFSpider.CrmWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WFSpider.CrmWebServiceReference.HelloWorldRequest inValue = new WFSpider.CrmWebServiceReference.HelloWorldRequest();
            inValue.Body = new WFSpider.CrmWebServiceReference.HelloWorldRequestBody();
            WFSpider.CrmWebServiceReference.HelloWorldResponse retVal = ((WFSpider.CrmWebServiceReference.ApiWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.HelloWorldResponse> WFSpider.CrmWebServiceReference.ApiWebServiceSoap.HelloWorldAsync(WFSpider.CrmWebServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.HelloWorldResponse> HelloWorldAsync() {
            WFSpider.CrmWebServiceReference.HelloWorldRequest inValue = new WFSpider.CrmWebServiceReference.HelloWorldRequest();
            inValue.Body = new WFSpider.CrmWebServiceReference.HelloWorldRequestBody();
            return ((WFSpider.CrmWebServiceReference.ApiWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse WFSpider.CrmWebServiceReference.ApiWebServiceSoap.InsertAgentGradeOprations(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest request) {
            return base.Channel.InsertAgentGradeOprations(request);
        }
        
        public void InsertAgentGradeOprations(WFSpider.CrmWebServiceReference.AgentGradeOperation[] itemList) {
            WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest inValue = new WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest();
            inValue.Body = new WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequestBody();
            inValue.Body.itemList = itemList;
            WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse retVal = ((WFSpider.CrmWebServiceReference.ApiWebServiceSoap)(this)).InsertAgentGradeOprations(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse> WFSpider.CrmWebServiceReference.ApiWebServiceSoap.InsertAgentGradeOprationsAsync(WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest request) {
            return base.Channel.InsertAgentGradeOprationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsResponse> InsertAgentGradeOprationsAsync(WFSpider.CrmWebServiceReference.AgentGradeOperation[] itemList) {
            WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest inValue = new WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequest();
            inValue.Body = new WFSpider.CrmWebServiceReference.InsertAgentGradeOprationsRequestBody();
            inValue.Body.itemList = itemList;
            return ((WFSpider.CrmWebServiceReference.ApiWebServiceSoap)(this)).InsertAgentGradeOprationsAsync(inValue);
        }
    }
}
