//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFSpider.CrmWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmWebService.ApiWebServiceSoap")]
    public interface ApiWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCompanyCms", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertCompanyCms(WFSpider.CrmWebService.CompanyCmsData[] itemList, string md5Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCompanyCms", ReplyAction="*")]
        System.Threading.Tasks.Task InsertCompanyCmsAsync(WFSpider.CrmWebService.CompanyCmsData[] itemList, string md5Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentGradeOprations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void InsertAgentGradeOprations(WFSpider.CrmWebService.AgentGradeOperation[] itemList, string md5Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertAgentGradeOprations", ReplyAction="*")]
        System.Threading.Tasks.Task InsertAgentGradeOprationsAsync(WFSpider.CrmWebService.AgentGradeOperation[] itemList, string md5Key);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompanyCmsData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private System.Nullable<int> cmsIdField;
        
        private string companyNameField;
        
        private string companyDespField;
        
        private string registerAddressField;
        
        private string realAddressField;
        
        private string companyIdNoField;
        
        private string guoneiWebNameField;
        
        private string guojiWebNameField;
        
        private string companyEmailField;
        
        private string legalPersonField;
        
        private string contactPersonField;
        
        private string contactPhoneField;
        
        private string bossBackgroundField;
        
        private string tTSAdminAccountField;
        
        private string salesNameField;
        
        private string tTSStatusDespField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> CmsId {
            get {
                return this.cmsIdField;
            }
            set {
                this.cmsIdField = value;
                this.RaisePropertyChanged("CmsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CompanyDesp {
            get {
                return this.companyDespField;
            }
            set {
                this.companyDespField = value;
                this.RaisePropertyChanged("CompanyDesp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RegisterAddress {
            get {
                return this.registerAddressField;
            }
            set {
                this.registerAddressField = value;
                this.RaisePropertyChanged("RegisterAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RealAddress {
            get {
                return this.realAddressField;
            }
            set {
                this.realAddressField = value;
                this.RaisePropertyChanged("RealAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CompanyIdNo {
            get {
                return this.companyIdNoField;
            }
            set {
                this.companyIdNoField = value;
                this.RaisePropertyChanged("CompanyIdNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string GuoneiWebName {
            get {
                return this.guoneiWebNameField;
            }
            set {
                this.guoneiWebNameField = value;
                this.RaisePropertyChanged("GuoneiWebName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string GuojiWebName {
            get {
                return this.guojiWebNameField;
            }
            set {
                this.guojiWebNameField = value;
                this.RaisePropertyChanged("GuojiWebName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CompanyEmail {
            get {
                return this.companyEmailField;
            }
            set {
                this.companyEmailField = value;
                this.RaisePropertyChanged("CompanyEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LegalPerson {
            get {
                return this.legalPersonField;
            }
            set {
                this.legalPersonField = value;
                this.RaisePropertyChanged("LegalPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ContactPerson {
            get {
                return this.contactPersonField;
            }
            set {
                this.contactPersonField = value;
                this.RaisePropertyChanged("ContactPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ContactPhone {
            get {
                return this.contactPhoneField;
            }
            set {
                this.contactPhoneField = value;
                this.RaisePropertyChanged("ContactPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BossBackground {
            get {
                return this.bossBackgroundField;
            }
            set {
                this.bossBackgroundField = value;
                this.RaisePropertyChanged("BossBackground");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TTSAdminAccount {
            get {
                return this.tTSAdminAccountField;
            }
            set {
                this.tTSAdminAccountField = value;
                this.RaisePropertyChanged("TTSAdminAccount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SalesName {
            get {
                return this.salesNameField;
            }
            set {
                this.salesNameField = value;
                this.RaisePropertyChanged("SalesName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string TTSStatusDesp {
            get {
                return this.tTSStatusDespField;
            }
            set {
                this.tTSStatusDespField = value;
                this.RaisePropertyChanged("TTSStatusDesp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AgentGradeOperation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string agentDomainField;
        
        private string agentNameField;
        
        private string promotionField;
        
        private string agentManagerField;
        
        private System.Nullable<int> totalTicketNumField;
        
        private System.Nullable<decimal> totalTicketField;
        
        private System.Nullable<decimal> passRateField;
        
        private System.Nullable<decimal> less60minRateField;
        
        private System.Nullable<decimal> orderAlterRateField;
        
        private System.Nullable<decimal> voluntaryRateField;
        
        private System.Nullable<decimal> involuntaryRateField;
        
        private System.Nullable<decimal> complainRateField;
        
        private System.Nullable<decimal> qapassRateField;
        
        private System.Nullable<decimal> phoneAnswerRateField;
        
        private System.Nullable<decimal> messageTimeoutRateField;
        
        private System.Nullable<decimal> qualificationField;
        
        private System.Nullable<decimal> whiteListField;
        
        private System.Nullable<decimal> totalScoreField;
        
        private int statusField;
        
        private System.Nullable<System.DateTime> statDateField;
        
        private string statMonthField;
        
        private string gradeField;
        
        private System.Nullable<int> curDateTicketCountField;
        
        private System.Nullable<System.DateTime> createTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string agentDomain {
            get {
                return this.agentDomainField;
            }
            set {
                this.agentDomainField = value;
                this.RaisePropertyChanged("agentDomain");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string agentName {
            get {
                return this.agentNameField;
            }
            set {
                this.agentNameField = value;
                this.RaisePropertyChanged("agentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string promotion {
            get {
                return this.promotionField;
            }
            set {
                this.promotionField = value;
                this.RaisePropertyChanged("promotion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string agentManager {
            get {
                return this.agentManagerField;
            }
            set {
                this.agentManagerField = value;
                this.RaisePropertyChanged("agentManager");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> totalTicketNum {
            get {
                return this.totalTicketNumField;
            }
            set {
                this.totalTicketNumField = value;
                this.RaisePropertyChanged("totalTicketNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> totalTicket {
            get {
                return this.totalTicketField;
            }
            set {
                this.totalTicketField = value;
                this.RaisePropertyChanged("totalTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> passRate {
            get {
                return this.passRateField;
            }
            set {
                this.passRateField = value;
                this.RaisePropertyChanged("passRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> less60minRate {
            get {
                return this.less60minRateField;
            }
            set {
                this.less60minRateField = value;
                this.RaisePropertyChanged("less60minRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> orderAlterRate {
            get {
                return this.orderAlterRateField;
            }
            set {
                this.orderAlterRateField = value;
                this.RaisePropertyChanged("orderAlterRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> voluntaryRate {
            get {
                return this.voluntaryRateField;
            }
            set {
                this.voluntaryRateField = value;
                this.RaisePropertyChanged("voluntaryRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> involuntaryRate {
            get {
                return this.involuntaryRateField;
            }
            set {
                this.involuntaryRateField = value;
                this.RaisePropertyChanged("involuntaryRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> complainRate {
            get {
                return this.complainRateField;
            }
            set {
                this.complainRateField = value;
                this.RaisePropertyChanged("complainRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> qapassRate {
            get {
                return this.qapassRateField;
            }
            set {
                this.qapassRateField = value;
                this.RaisePropertyChanged("qapassRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> phoneAnswerRate {
            get {
                return this.phoneAnswerRateField;
            }
            set {
                this.phoneAnswerRateField = value;
                this.RaisePropertyChanged("phoneAnswerRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> messageTimeoutRate {
            get {
                return this.messageTimeoutRateField;
            }
            set {
                this.messageTimeoutRateField = value;
                this.RaisePropertyChanged("messageTimeoutRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<decimal> qualification {
            get {
                return this.qualificationField;
            }
            set {
                this.qualificationField = value;
                this.RaisePropertyChanged("qualification");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<decimal> whiteList {
            get {
                return this.whiteListField;
            }
            set {
                this.whiteListField = value;
                this.RaisePropertyChanged("whiteList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> totalScore {
            get {
                return this.totalScoreField;
            }
            set {
                this.totalScoreField = value;
                this.RaisePropertyChanged("totalScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<System.DateTime> statDate {
            get {
                return this.statDateField;
            }
            set {
                this.statDateField = value;
                this.RaisePropertyChanged("statDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string statMonth {
            get {
                return this.statMonthField;
            }
            set {
                this.statMonthField = value;
                this.RaisePropertyChanged("statMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string grade {
            get {
                return this.gradeField;
            }
            set {
                this.gradeField = value;
                this.RaisePropertyChanged("grade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<int> CurDateTicketCount {
            get {
                return this.curDateTicketCountField;
            }
            set {
                this.curDateTicketCountField = value;
                this.RaisePropertyChanged("CurDateTicketCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("CreateTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiWebServiceSoapChannel : WFSpider.CrmWebService.ApiWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiWebServiceSoapClient : System.ServiceModel.ClientBase<WFSpider.CrmWebService.ApiWebServiceSoap>, WFSpider.CrmWebService.ApiWebServiceSoap {
        
        public ApiWebServiceSoapClient() {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertCompanyCms(WFSpider.CrmWebService.CompanyCmsData[] itemList, string md5Key) {
            base.Channel.InsertCompanyCms(itemList, md5Key);
        }
        
        public System.Threading.Tasks.Task InsertCompanyCmsAsync(WFSpider.CrmWebService.CompanyCmsData[] itemList, string md5Key) {
            return base.Channel.InsertCompanyCmsAsync(itemList, md5Key);
        }
        
        public void InsertAgentGradeOprations(WFSpider.CrmWebService.AgentGradeOperation[] itemList, string md5Key) {
            base.Channel.InsertAgentGradeOprations(itemList, md5Key);
        }
        
        public System.Threading.Tasks.Task InsertAgentGradeOprationsAsync(WFSpider.CrmWebService.AgentGradeOperation[] itemList, string md5Key) {
            return base.Channel.InsertAgentGradeOprationsAsync(itemList, md5Key);
        }
    }
}
